language: python
cache: pip
sudo: false
env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
python:
  - 3.6
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -q django==$DJANGO_VERSION
script: make coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT